### ISSUE TITLE
Onchain Summer Bounty → OpenSea Base Mint Ingestor

### ISSUE THREAD

**Issue by christinehall** [floornfts/mobile-minting#7]
- Generate a `MintTemplate` that supports an **OpenSea mint on Base** from a URL, such as `https://opensea.io/collection/get-based-3/overview`
- You can test your metadata ingestion against this open mint → ["GET BASED" by 1CrypticPoet](https://opensea.io/collection/get-based-3/overview)
- Bounty for this ingestor is 500 USDC, paid upon:
  - Successful approval & merge of the pull request
  - Ingestion of one mint into Mobile Minting ✨

**Comment by mawutory** [comment]
@christinehall, after days of research on this, I have concluded that we cannot use a URL to create an OpenSea Base Mint Ingestor, due to the structure of the URL. However, we can create an Ingestor from a contract address. It is also possible to build the URL from the contract address. 

So we can build the URL from the contract address only. chainId is already known.

I want to submit a draft PR.

**Comment by chrismaddern** [comment]
This issue is being closed for now. It appears incompatible with Mobile Minting without additional permissions / contract interfaces.

**Comment by chrismaddern** [comment]
This issue is being closed for now. It appears incompatible with Mobile Minting without additional permissions / contract interfaces.
